config/routes.rb
Rails.application.routes.draw do
  root 'page#home'
  get 'home' => 'page#home'

  resources :recipes do
    member do
      post 'like'
    end
  end

  resources :chefs, except: :new

  get '/register', to: 'chefs#new', as: :chef_register

  get 'login' => 'logins#new'
  post 'login' => 'logins#create'
  get 'logout' => 'logins#destroy'

end

app/models/chef.rb
class Chef < ActiveRecord::Base
  has_many :recipes
  has_many :likes
  before_save {self.email = email.downcase}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
  validates :chefname, presence: true, length: {minimum: 5, maximum: 20}
  validates :email, presence: true, length: {maximum: 50}, uniqueness: {case_sensitive: false},
            format: {with: VALID_EMAIL_REGEX}
  has_secure_password
end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :chef
  belongs_to :recipe

  validates_uniqueness_of :chef, scope: :recipe

  def check_like_or_dislike(chef_id, recipe_id)

  end

end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  belongs_to :chef
  has_many  :likes
  validates :name, presence: true, length: {minimum: 5, maximum: 100}
  validates :summary, presence: true, length: {minimum: 10, maximum: 150}
  validates :description, presence: true, length: {minimum: 20, maximum: 4000}
  validates :chef_id, presence: true
  validates :picture, presence: true
  mount_uploader :picture, PictureUploader
  validate :picture_size

  def thumbs_up_total
    self.likes.where(like: true).size
  end

  def thumbs_down_total
    self.likes.where(like: false).size
  end

  private
  def picture_size
    if picture.size > 5.megabyte
      errors.add(:picture, "should be less than 5MB")
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?, :require_user

  def current_user
    @current_user ||= Chef.find(session[:chef_id]) if session[:chef_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:danger] = "Please login first"
      redirect_to root_path
    end
  end

end

app/controllers/chefs_controller.rb
class ChefsController < ApplicationController
  before_action :require_user, except: [:new, :create]
  def index
    @chef = Chef.paginate(page: params[:page], per_page: 5)
  end

  def new
    @chef = Chef.new
  end

  def create
    @chef = Chef.new(chef_params)

    if @chef.save
      flash[:success] = "Thank you for Register"
      redirect_to root_path
    else
      render 'new'
    end
  end

  private

  def chef_params
    params.require(:chef).permit(:chefname, :email, :password)
  end

end

app/controllers/logins_controller.rb
class LoginsController < ApplicationController
  def new
  end

  def create
    chef = Chef.find_by(email: params[:email])
    if chef && chef.authenticate(params[:password])
      session[:chef_id] = chef.id
      flash[:success] = "Successfully login"
      redirect_to recipes_path
    else
      flash[:danger] = "Invaild Email_id or Password"
      render 'new'
    end
  end

  def destroy
    session[:chef_id] = nil
    flash[:success] = "You have logout"
    redirect_to root_path
  end
end

app/controllers/page_controller.rb
class PageController < ApplicationController
	def home
		redirect_to recipes_path if logged_in?
	end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: [:show, :edit, :update, :like]
  before_action :require_user
  before_action :require_same_user, only: [:edit, :update]

  def index
    @recipe = Recipe.paginate(page: params[:page], per_page: 6)
  end

  def show
    @recipe = Recipe.find(params[:id])
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = Recipe.new(recipe_params)
    @recipe.chef   = Chef.find(1)

    if @recipe.save
      flash[:success] = "Your Recipe successfully save"
      redirect_to recipes_path
    else
      render 'new'
    end
  end

  def edit
    @recipe = Recipe.find(params[:id])
  end

  def update
    if @recipe.update(recipe_params)
      flash[:success] = "You Recipe successfully Updated"
      redirect_to recipe_path(@recipe)
    else
      render 'edit'
    end
  end

  def like
    like = Like.create(like: params[:like], chef: Chef.first, recipe: @recipe)
    if like.valid?
      flash[:success] = "Your selection was successfull"
      redirect_to :back
    else
      flash[:danger] = "You can like/dislike a recipe once"
      redirect_to :back
    end
  end

  private
  def recipe_params
    params.require("recipe").permit("name", "summary", "description", "picture")
  end

  def set_recipe
    @recipe = Recipe.find(params[:id])
  end

  def require_same_user
    if current_user != @chef
      flash[:danger] = "You don't have access to that service"
      redirect_to root_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/views/chefs/_form.html.erb
<div class="row">
  <div class="col-sm-offset-3 col-sm-7 ">
    <p>
    <%= render 'shared/error', obj: @chef%>

    <%= form_for @chef do |chef|%>
        <div class="form-group row">
          <%= chef.label :User_name, class: "col-sm-4 form-control-label text-center" %>
          <div class="col-sm-8">
            <%= chef.text_field :chefname, placeholder: "User Name", class: "form-control"%>
          </div>
        </div>

        <div class="form-group row">
          <%= chef.label :Email, class: "col-sm-4 form-control-lable text-center" %>
          <div class="col-sm-8">
            <%= chef.email_field :email, placeholder: "Email", class: "form-control"%>
          </div>
        </div>

        <div class="form-group row">
          <%= chef.label :password, class: "col-sm-4 form-control-label text-center" %>
          <div class="col-sm-8">
            <%= chef.password_field :password, placeholder: "Enter password", class: "form-control"%>
          </div>
        </div>

        <div class="form-group row">
          <%= chef.label :password_conformation, class: "col-sm-4 form-control-label text-center" %>
          <div class="col-sm-8">
            <%= chef.password_field :password_conformation, placeholder: "Re enter password", class: "form-control"%>
          </div>
        </div>
        <%= chef.submit form_name, class: "btn btn-success btn-md" , style: "margin-left: 30%; width: 40%; margin-bottom: 10px" %>
    <% end %>
    </p>
  </div>
</div>

app/views/chefs/index.html.erb
<div class="text-center">
  <span style="margin-left: 100px"><%= will_paginate @chef%></span>
    <% @chef.each do |chef|%>
      <div class="row">
          <div class="card col-sm-3 col-sm-offset-5">
            <%= image_tag( "http://gurucul.com/wp-content/uploads/2015/01/default-user-icon-profile.png", class:"card-img-top")%>
            <div class="card-block">
              <label>Chef Name :- </label>
              <%= chef.chefname %>
            </div>
          </div>
      </div>
    <% end %>
</div>

app/views/chefs/new.html.erb
<div class="container-fluid ">
  <h3 class="recipe-title text-center">Register to MyRecipes.com</h3>
  <hr>
  <%= render 'form', form_name: "SignUp"%>
</div>

app/views/layouts/_footer.html.erb
<div class="footer">
  <p>&copy MyRecipes 2015</p>
</div>

app/views/layouts/_messages.html.erb
<% flash.each do |message_type, message|%>
    <div class="alert alert-<%=message_type%>" style="margin-top: 10px">
      <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
      <strong><%= message_type.capitalize%></strong>! <%= message%>
    </div>
<%end%>

app/views/layouts/_navigation.html.erb
<nav role="navigation" class="navbar navbar-default">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" data-target="#navbarCollapse" data-toggle="collapse" class="navbar-toggle">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a href="#" class="navbar-brand" id="logo">MyRecipes</a>
  </div>
  <!-- Collection of nav links, forms, and other content for toggling -->
  <div id="navbarCollapse" class="collapse navbar-collapse">
    <ul class="nav navbar-nav">
      <% if logged_in? %>
          <li class=""><a href="/recipes">Recipes</a></li>
          <li class=""><a href="/recipes/new">Create New Recipes</a></li>
      <%else%>
          <li class=""><a href="/home">Home</a></li>
      <%end%>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <% if logged_in? %>
      <li><a href="/logout">Logout</a></li>
     <%else%>
      <li><a href="/login">Login</a></li>
     <%end%>
    </ul>
    <form role="search" class="navbar-form navbar-right">
      <div class="form-group">
        <input type="text" placeholder="Search" class="form-control">
      </div>
    </form>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyRecipes</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>


  <!-- Required meta tags always come first -->
  <meta charset="utf-8">
  <meta name="myrecipes" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta http-equiv="x-ua-compatible" content="ie=edge">

</head>
<body>
	<div class="row">
		<div class="container">
            <%= render 'layouts/navigation'%>
			<div id="body_content">
                <%= render 'layouts/messages'%>
				<%= yield %>
			</div>
            <%= render 'layouts/footer'%>
		</div>
	</div>
</body>
</html>

app/views/logins/new.html.erb
<div class="container-fluid " xmlns="http://www.w3.org/1999/html">
  <h3 class="recipe-title text-center">MyRecipes.com</h3>
  <hr>

  <div class="text-center row">
    <div class="col-sm-offset-4 col-sm-5">
      <div class="login_form">
        <p><h3 class="recipe-title" style="padding-bottom: 8px">login</h3></p><hr>
        <%= form_tag '/login' do %>
          <div class="form-group row">
            <label class="col-sm-5 form-control-label text-center">Email ID</label>
            <div class="col-sm-7">
              <%= text_field_tag :email, nil, placeholder: "User Name", class: "form-control"%>
            </div>
          </div>

          <div class="form-group row">
            <label class="col-sm-5 form-control-label text-center">Password</label>
            <div class="col-sm-7">
              <%= text_field_tag :password, nil, placeholder: "Password", class: "form-control"%>
            </div>
          </div>

          <%= submit_tag "Sigin", class: "btn btn-success btn-md", style: "width: 70%; margin-bottom: 10px" %>
        <%end%>
        <h4><%= link_to "Register New User", chef_register_path, style: "margin-top: 22px"%></h4>
     </div>
    </div>
  </div>

</div>

app/views/page/home.html.erb
<div class="text-center jumbotron">
	<h2>Welcome to MyRecipes.com</h2>
	<a href="/register" class="btn btn-primary btn-md btn-success" id="sign_up"><span class="glyphicon glyphicon-user"></span> Sign up</a>
</div>
<div class="row">
	<div class="col-sm-12 col-md-4 col-lg-4">
		<div class="header_content">
			<h3>dosa recipe and dosa batter in a mixer-grinder</h3>
		</div>
		<div class="body_content">
			dosa recipe and dosa batter in a mixer-grinder - dosa is a famous breakfast or snack both in india as well as outside india. dosas are basically rice and lentil crepes. there are many varieties of dosa and the texture ranges from crisp to soft to fluffy to light. these varying textures are due to the proportion of the rice, urad dal and other ingredients used in the dosa batter …
		</div>
		<div class="footer_content text-center">
			<a class="details_recipe">Read More</a>
		</div>
	</div>
	<div class="col-sm-12 col-md-4 col-lg-4">
		<div class="header_content">
			<h3>dosa recipe and dosa batter in a mixer-grinder</h3>
		</div>
		<div class="body_content">
			dosa recipe and dosa batter in a mixer-grinder - dosa is a famous breakfast or snack both in india as well as outside india. dosas are basically rice and lentil crepes. there are many varieties of dosa and the texture ranges from crisp to soft to fluffy to light. these varying textures are due to the proportion of the rice, urad dal and other ingredients used in the dosa batter …
		</div>
		<div class="footer_content text-center">
			<a class="details_recipe">Read More</a>
		</div>
	</div>	
	<div class="col-sm-12 col-md-4 col-lg-4">
		<div class="header_content">
			<h3>dosa recipe and dosa batter in a mixer-grinder</h3>
		</div>
		<div class="body_content">
			dosa recipe and dosa batter in a mixer-grinder - dosa is a famous breakfast or snack both in india as well as outside india. dosas are basically rice and lentil crepes. there are many varieties of dosa and the texture ranges from crisp to soft to fluffy to light. these varying textures are due to the proportion of the rice, urad dal and other ingredients used in the dosa batter …
		</div>
		<div class="footer_content text-center">
			<a class="details_recipe">Read More</a>
		</div>
	</div>
</div>

app/views/recipes/_form.html.erb
<div class="row">
  <div class="col-sm-offset-3 col-sm-6 ">
    <p>
    <%= render 'shared/error', obj: @recipe%>

    <%= form_for(@recipe, html: {multipart: true}) do |recipe|%>
        <div class="form-group row">
          <%= recipe.label :Recipe_Name, class: "col-sm-4 form-control-label text-center" %>
          <div class="col-sm-8">
            <%= recipe.text_field :name, placeholder: "Recipe Name", class: "form-control"%>
          </div>
        </div>

        <div class="form-group row">
          <%= recipe.label :Summary, class: "col-sm-4 form-control-lable text-center" %>
          <div class="col-sm-8">
            <%= recipe.text_field :summary, placeholder: "Summary", class: "form-control"%>
          </div>
        </div>

        <div class="form-group row">
          <%= recipe.label :Description, class: "col-sm-4 form-control-label text-center" %>
          <div class="col-sm-8">
            <% rows = (@recipe.description.blank? || @recipe.description.size < 80)? 7 : 18%>
            <%= recipe.text_area :description, placeholder: "Details description", class: "form-control", cols: "30", rows: rows %>
          </div>
        </div>

        <div class="form-group row">
          <%= recipe.label :Upload_File, class: "col-sm-4 form-control-label text-center" %>
          <div class="col-sm-8">
            <%= recipe.file_field :picture, placeholder: "Image upload", class: "form-control", accept: "image/jpg,image/jpge,image/gif,image/png"%>
          </div>
        </div>

        <%= recipe.submit form_name, class: "btn btn-success btn-md" , style: "margin-left: 28%" %>
    <% end %>
    </p>
  </div>
</div>

app/views/recipes/edit.html.erb
<div class="container-fluid ">
  <h3 class="recipe-title text-center">Edit Recipe</h3>
  <hr>
  <%= render 'form', form_name: "Update Recipe"%>
</div>

app/views/recipes/index.html.erb
<div class="container">
    <h3 class="recipe-title">All Recipes</h3>
    <hr>

    <%= will_paginate @recipe%>
    <div class="row">
      <div class="container">
        <%@recipe.reverse.each do |recipe|%>
          <div class="col-md-4">
            <div class="card">
              <%= image_tag(recipe.picture.url, class: "card-img-top", width: "336px", height: "150px", alt: "Card image cap") if recipe.picture?%>
              <div class="card-block">
                <h4 class="card-title"><%= truncate(recipe.name, length: 40)%></h4>
                <div class="card-text">
                  <p><%= truncate( recipe.summary,length: 50) %></p>
                  <p>
                    <small><%= time_ago_in_words(recipe.created_at)%>
                    <i>Created by <b><a href=""><%=recipe.chef.chefname%></a></b></i>
                    </small>
                  </p>
                </div>
                <a href="<%=recipe_path(recipe)%>" class="btn btn-warning-outline">Read More</a>
                <div class="pull-right" style="margin-top: 10px">
                  <%= link_to like_recipe_path(recipe, like: true), method: :post do %>
                    <span class="glyphicon glyphicon-thumbs-up" aria-hidden="true">
                      <%= recipe.thumbs_up_total %>&nbsp
                    </span>
                  <%end%>
                  <%= link_to like_recipe_path(recipe, like: false), method: :post do %>
                    <span class="glyphicon glyphicon-thumbs-down" style="color: red" aria-hidden="true">
                      <%= recipe.thumbs_down_total %>
                    </span>
                  <%end%>
                </div>
              </div>
            </div>
          </div>
        <%end%>
      </div>
    </div>
</div>

app/views/recipes/new.html.erb
<div class="container-fluid ">
  <h3 class="recipe-title text-center">Create New Recipe</h3>
  <hr>
  <%= render 'form', form_name: "Create New Recipe"%>
</div>

app/views/recipes/show.html.erb
<div class="container-fluid">
  <h3 class="recipe-title">
    <%=@recipe.name%>
    <%= (link_to "Edit Recipe", edit_recipe_path(@recipe), class: "btn btn-success", style: "float: right") if current_user == @recipe%>
  </h3><hr>
  <div class="row">
    <div class="col-md-8 card">
      <p class="recipe-text card-block ">
        <h4><%= @recipe.summary%></h4>
        <hr>
        <p><strong>Steps</strong></p>
        <p>
          <%=simple_format(@recipe.description)%>
          <div class="pull-right">
            <%= link_to like_recipe_path(@recipe, like: true), method: :post do %>
                <span class="glyphicon glyphicon-thumbs-up" aria-hidden="true">
                  <%= @recipe.thumbs_up_total %>&nbsp
                </span>
            <%end%>
            <%= link_to like_recipe_path(@recipe, like: false), method: :post do %>
                <span class="glyphicon glyphicon-thumbs-down" style="color: red" aria-hidden="true">
                  <%= @recipe.thumbs_down_total %>
                </span>
            <%end%>
          </div>
        </p>
      <p>
    </div>
    <div class="col-md-4 " style="padding-left: 15px">
      <div class="card">
          <div class="card-block text-center" >
            <%= image_tag(@recipe.picture.url, class: "card-img-top", width: "320px", height: "200px") if @recipe.picture?%>
          </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_error.html.erb
<% if obj.errors.any? %>
    <div class="alert alert-danger well">
      <ul>
        <% obj.errors.full_messages.each do |error| %>
            <li><%=error%></li>
        <%end%>
      </ul>
    </div>
<%end%>